// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztahumjvgedfnukdfxjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0YWh1bWp2Z2VkZm51a2RmeGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjE2NjAsImV4cCI6MjA2NDA5NzY2MH0.VH8tGBfL6_0Xhfs2jE_RlEiR7JxRxu_o-mYlvlY4NuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);